version: 2.1
jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.1-node
      environment:
        RAILS_ENV: test
    - image: circleci/mysql:5.7-ram
      environment:
        MYSQL_DATABASE: Share_Childcare_test
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_ROOT_HOST: '%'
        MYSQL_USER: root
    working_directory: ~/ShareChildcare
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          gem install bundler -v 1.17.3
          bundle install --jobs=4 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}
    # DB作成
    - run:
        name: Prepare db
        command: |
          bin/rails db:schema:load --trace
    # テスト時(Rspec)
    - run:
        name: Run rspec
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
          bundle exec rspec --format progress --color --format documentation
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results
        
    - add_ssh_keys:
        fingerprints:
          - "21:f9:2e:b2:73:a2:98:ad:29:6f:b2:8c:8f:f9:41:56"

    - deploy:
        name: Capistrano deploy
        command: |
          if [ "${CIRCLE_BRANCH}" != "master" ]; then
            exit 0
          fi
          bundle exec cap production deploy
