default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  socket: /tmp/mysql.sock
  host: db

development:
  <<: *default
  database: Share_Childcare_development

test:
  <<: *default
  database: Share_Childcare_test

production:
  <<: *default
  database: Share_Childcare_production
  username: Share_Childcare
  password: <%= ENV['SHARE_CHILDCARE_DATABASE_PASSWORD'] %>
