default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  socket: /tmp/mysql.sock


development:
  <<: *default
  database: Share_Childcare_development
  host: db
  

test:
  <<: *default
  database: Share_Childcare_test
  password: 
  host: db
  # host: <%= ENV['MYSQL_ROOT_HOST'] || '127.0.0.1' %>

production:
  <<: *default
  database: Share_Childcare_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
  host: share-childcare-web.cprwrnj9czrb.ap-northeast-1.rds.amazonaws.com
