default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  socket: /tmp/mysql.sock


development:
  <<: *default
  database: Share_Childcare_development
  host: db

test:
  <<: *default
  database: Share_Childcare_test
  host: <%= ENV['MYSQL_ROOT_HOST'] || '127.0.0.1' %>

production:
  <<: *default
  database: Share_Childcare_production
  username: Share_Childcare
  password: <%= ENV['SHARE_CHILDCARE_DATABASE_PASSWORD'] %>
  host: db
